// Contains information pulled from http://www.learntarot.com/cards.htm

const cardData = [
  {cardName: "Two of Cups",
    cardImage: './CardImages/cups_2.jpg',
    cardDescription: "<p>To understand the 2 of Cups, all you have to do is look at its image. A man and a woman are gazing at each other, ready to share their cups (emotions). Here is the very picture of romantic and sexual attraction. The energy between these two is almost palpable. The Two of Cups shows the beauty and power that is created when two come together. This is the card that lovers want to see, and, in fact, the Two of Cups is the minor arcana equivalent of the Lovers in many ways.</p><p>The Two of Cups has a deeper meaning as well. Whenever two forces are drawn together, there is the potential for bonding. This card can stand for the union of any two entities - people, groups, ideas, or talents. In readings, the Two of Cups tells you to look for connections in your life, especially those that are one-on-one. Now is not the time to separate or stay apart. It is the time to join with another and work as a partnership. If you are in conflict, look for truce and the chance to forgive and be forgiven. If you are struggling with two choices or tendencies within yourself, seek to reconcile them.</p><p>Usually, the Two of Cups is welcome in a reading, but it can also sound a note of warning. The energy of Two can be very compelling. If you have ever stood next to two people in love, you know what I'm talking about. They create between themselves a world of their own that can feel exclusionary to outsiders. \"Two's company; three's a crowd.\" Make sure that the tendency to pair off is not creating disharmony in your situation."
  },

  {cardName: "Three of Cups",
    cardImage: './CardImages/cups_3.jpg',
    cardDescription: "<p>There are three cards in the tarot that focus on the group - each from a different point of view. For the Hierophant, it\'s the formal approach. For the Three of Pentacles it\'s teamwork, and for the Three of Cups, it\'s emotions. What does it feel like to join with others? What is friendship and community? These are the questions answered by the Three of Cups.</p><p>On this card, we see three women dancing together in a circle. Their arms reach out to each other to connect their feelings (Cups). In many settings, women create and nurture the social glue that bonds people together. These dancing women are a symbol of coming together in love. (Of course, these feelings do not only relate to woman.)</p><p>In readings, the Three of Cups can signify a friend or the feelings associated with friendship. This card can represent community - the network of support created when we interact with others. It can be any group in which the members feel a bond. When you see the Three of Cups, examine your attachments to the groups in your life from an emotional point of view. Consider reaching out to give or receive help. This card stands for all forms of support, including formal aid such as counseling and other social services.</p><p>The women on the Three of Cups also express joy and high spirits. Such feelings are not limited to groups, but can be especially strong there. Celebrations spontaneously arise when people feel connected, loved and secure. The Three of Cups can stand for a mood or experience that makes you feel like dancing and singing.</p>"
  },

  {},
  {},
]
